### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by jbreitbart**

### CODE REVIEW

**Comment by jbreitbart** [comment]
I am using `perfcnt` and as a dependency also this crate in one of my projects. Using raw-cpuid < 0.9.0 results in an error when running `cargo audit` (RUSTSEC-2021-0013).

I cannot run `cargo test` (even without my changes) as it reports

```
  --> /home/jbreitbart/.cargo/registry/src/github.com-1ecc6299db9ec823/x86-0.21.0/src/lib.rs:96:5
   |
96 |     asm!("rdpid $0" : "=r"(pid));
   |     ----^^^^^^^^^^^^^^^^^^^^^^^^^
   |     |
   |     help: replace with: `llvm_asm!`
   |
   = note: consider migrating to the new asm! syntax specified in RFC 2873
   = note: alternatively, switch to llvm_asm! to keep your code working as it is

error: aborting due to 70 previous errors
```

I am not sure why this is happening. Are the tests working on your machine?

**Comment by gz** [comment]
Thanks for submitting this!

**Comment by jbreitbart** [comment]
@gz Thanks for merging. Would you be interested in a dependabot config that keeps your dependencies updated automatically? The bot would create PR like https://github.com/jbreitbart/criterion-perf-events/pull/3

**Comment by gz** [comment]
@jbreitbart yes that sounds great, is there a way to sign up for this?

**Comment by jbreitbart** [comment]
It's part of Github Actions. I'll send a PR with a config file for the bot later today/tomorrow. IIRC that is all you need to have the bot monitor the repository.

**Pull request merged**
