### PR TITLE
Add Frame and PageFrame types

### PR DESCRIPTION
**Pull request by dschatzberg**
This provides common types for physical page frames and ranges of
frames. Adding these types into the crate pave the way for us to add
additional paging functions.

### CODE REVIEW

**Comment by dschatzberg** [comment]
I considered using https://doc.rust-lang.org/std/ops/struct.Range.html to implement `PageRange`, but ended up not doing so. Particularly, the `Step` trait needs some work to support stepping by a different type than the element themselves.

**Comment by gz** [comment]
Hi Dan, I'm rather reluctant to merge this as I feel the representation of physical memory is something not in scope of this crate. The reason is that the representation of a Frame is highly implementation dependent. For example the current patch only represents 4 KiB frames and would not work for representing consecutive 2 MiB or 1 GiB regions for large pages (in that situation, ideally a Frame would have a base with some alignment constraints and a size). My feeling is that it physical memory management belongs more to the OS rather than an x86 crate. What is your tought process for putting it here?
That beeing said I think a libcore based crate that manages physical memory in a flexible way would be a very useful thing to have.

**Comment by dschatzberg** [comment]
@gz My thought process is that a lot of OSs will have different policies for managing physical memory, paging, etc, but there are a lot of common architecturally defined mechanisms which most of them have to do. For example, walking a page table, mapping a physical frame at a particular virtual page. This code can be tricky and so I think a well-tested crate which incorporates this functionality would be beneficial. This patch really represents one of the first steps towards adding more of this functionality to this crate.

I completely understand if you want this crate to really just be structural definitions and not implement anything more. I just want to be clear that my goal is not to implement any policy here (like how memory is managed), just some additional functions which can be used to do so. I think it makes sense to add additional types for the larger page sizes. I was just starting with something small to open this discussion.

**Comment by dschatzberg** [comment]
To make the discussion a bit more concrete, I can see us adding a method on PML4 as follows:

    fn translate<F>(vaddr: VAddr, f: F) -> Option<PAddr>
      where F: Fn(Frame) -> * mut u8;

or something like

    fn map_range<F, A>(frames: FrameRange, vaddr: VAddr, f: F, a: A, use_large_page: bool) -> bool
      where F: Fn(frame) -> * mut u8,
            A: Fn() -> Frame

**Pull request closed without merging**
