### PR TITLE
Fix asm syntax of some VMX instructions

### PR DESCRIPTION
**Pull request by equation314**

### CODE REVIEW

**Comment by gz** [comment]
Thanks! I wonder if there is something you're running this code with that we can use to test the x86 crate in the future (as I'm not actively using this code it's hard to test it :))?

**Comment by equation314** [comment]
I use this crate in our hypervisor project https://github.com/rcore-os/RVM1.5.
It won't work after upgrading the crate to v0.45.0.
You can see the difference between v0.44.0 and v0.45.0 in the disassembled code.

**Comment by gz** [comment]
Thanks, released as 0.46.0

**Comment by dancrossnyc** [comment]
Oops; my bad. Sorry, I didn't have an easy means to test that, either. (I really need to put together that Xeon test box....)

**Comment by gz** [comment]
no worries, it's just the hypervisor and vmx code that's not really covered well by what I'm running I think, but it's great to see that others are using it and finding the bugs quickly!

**Pull request merged**
