### PR TITLE
Structures are not considered immediates anymore

### PR DESCRIPTION
**Pull request by phil-opp**
This fixes the build error on latest nightly.

See rust-lang/rust#39083 and especially [this comment](https://github.com/rust-lang/rust/issues/39083#issuecomment-272935193) for details.

### CODE REVIEW

**Comment by phil-opp** [comment]
Merging this myself, since it breaks [redox](https://github.com/redox-os/redox/issues/828) and [intermezzOS](https://github.com/intermezzOS/kernel/pull/107). I hope this is okay with you, @gz.

**Comment by phil-opp** [comment]
@gz could you publish a new crates.io version?

**Comment by gz** [comment]
@phil-opp Absolutely, thanks for fixing this. I released versions 0.8.1, 0.7.2 and 0.6.2 which contains your patch.

**Comment by phil-opp** [comment]
@gz Great, thanks a lot!

**Pull request merged**
