### PR TITLE
Move cache flushing operations into shared

### PR DESCRIPTION
**Pull request by rexlunae**
The cache flushing operations should be in shared because they apply to 32 and 64 bit processors in exactly the same way.

### CODE REVIEW

**Comment by JustAPerson** [comment]
This PR also includes adding a `nop`.
 While doing so, might I recommend including multi-bytes nops? Both Intel and AMD have recommended some preferred instruction sequences. Multi-byte nops are faster to decode than an equivalent sequence of `xchg eax, eax` traditional nops.

For example, I've had Rust/LLVM generate this sequence for loop alignment:
```
12:    66 66 66 66 66 2e 0f     data16 data16 data16 data16 nop WORD PTR cs:[eax+eax*1+0x0]
19:    1f 84 00 00 00 00 00
```

Intel describes up to 9-byte sequences ([see here, page 163/165](http://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-vol-2b-manual.pdf)) while AMD describes up to 15-byte sequences ([see here, page 17](http://amd-dev.wpengine.netdna-cdn.com/wordpress/media/2012/10/SOG_16h_52128_PUB_Rev1_1.pdf)). They have different performance characteristics on different microarchitectures and may potentially trigger undefined instruction exceptions on older hardware, so obviously they should be used with care. But it seems like an interesting addition to the library.

Here are the sequences described by AMD:
```
 1     90
 2     66 90
 3     0F 1F 00
 4     0F 1F 40 00
 5     0F 1F 44 00 00
 6     66 0F 1F 44 00 00
 7     0F 1F 80 00 00 00 00
 8     0F 1F 84 00 00 00 00 00
 9     66 0F 1F 84 00 00 00 00 00
 10    66 66 0F 1F 84 00 00 00 00 00
 11    66 66 66 0F 1F 84 00 00 00 00 00
 12    66 66 66 66 0F 1F 84 00 00 00 00 00
 13    66 66 66 66 66 0F 1F 84 00 00 00 00 00
 14    66 66 66 66 66 66 0F 1F 84 00 00 00 00 00
 15    66 66 66 66 66 66 66 0F 1F 84 00 00 00 00 00
```

**Comment by JustAPerson** [comment]
@rexlunae if you don't mind, I can add the extra stuff I mentioned sometime today or tomorrow.

**Comment by rexlunae** [comment]
That sounds good to me.

**Comment by Ericson2314** [comment]
Maybe we need a `nop` module then :). Make that a separate PR?

**Comment by rexlunae** [comment]
I've reverted the nop function from my fork to clean up the PR.  I'll probably push through a separate PR for that at some point in the near future incorporating some of these suggestions.

**Comment by Ericson2314** [comment]
Looks good to me then! Hopefully @gz can merge soon. I had only bothered to make shared modules for things in both libcpu and this, so there could be other stuff in bits64 to move to shared.

**Comment by gz** [comment]
Hi, Looks good to me. Many thanks for submitting this pull request!

**Pull request merged**
