### PR TITLE
Fix #15: Combine with https://github.com/Tobba/libcpu 

### LINKED ISSUE #15: Combine with https://github.com/Tobba/libcpu
There seems to be good overlap with between this and that. This is more complete, but I find the lack of 32-bit vs 64-bit `#![cfg(..)]`s confusing (or is only 64-bit meant to be supported?).

CC @Tobba

### PR DESCRIPTION
**Pull request by Ericson2314**
I'm trying to pull interface ideas from both libraries, while throwing in a few of my own---aka making a mess of backwards compat. Let me know what you all think so far.

It looks like a lot of commits as a I did a subtree merge to preserve the history of both libraries. Look at the `Combine Interface:*` commits for actual API changes.

### CODE REVIEW

**Comment by gz** [comment]
Wow thanks for the doing the work, this looks pretty good, I will have a closer look tonight! But I'm in general very excited about having both, 32 and 64 bit support in this crate.

**Comment by gz** [comment]
I had a closer look, so far I think it looks good. We need to think about a bit what rules will guide the interface unification for 32 vs. 64bit. One thing that comes to mind is: can the public interface be identical for both architectures (would be nice if this is feasible but I'm not sure)?

Also let me know if I can help with any of the refactoring. I should have some time for a piece of the work.

**Comment by Ericson2314** [comment]
@gz: things in `shared` currently have identical interface and implementation, and things in `bit{32,64}` might have the same interface, and definitely the same implementation. I figured this was a good place to begin.

In the other thread you mention:

> One thing to consider is that the crate would ideally be able provide access to both, 32-bit and 64-bit data structure descriptions on a 64bit or 32bit host system.

I like that idea, say with a `::types` module. One issue is some types which would be defined with `usize` or pointer types then only work for the current module. I suppose I could define them with generics?

Regardless, I like the idea of doing `shared` vs `bits{32, 64}` for implementation, not interface. At least the tiny `bits*::{rflags, segmentation}` modules can go away.

If you want to hop on IRC, I'd be happy to hash out anything else that needs to be done.

**Comment by Ericson2314** [comment]
Ok, I think this is good to go--all of libcpu has been incorporated! I got rid of the tiny mode-specific rflags and segmentation modules as I had proposed. There may still be parts of x86 that can be generalized to work for 32-bit or even work out of the box, and it would be nice to get Travis to do 32-bit builds, but this is follow-up work.

**Comment by Ericson2314** [comment]
Realized I messed up `set_cs`, should be fixed now.

**Comment by gz** [comment]
Merged. Thanks, I will release a new cargo version soon!

**Comment by Ericson2314** [comment]
Thanks so much!

**Pull request merged**
